name: Flutter CI
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Flutter Analyze and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '17.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Clean Flutter build
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    # ãƒªãƒ¢ãƒ¼ãƒˆãƒªãƒã‚¸ãƒˆãƒªã§GitHub Secretsã‹ã‚‰.envãƒ•ã‚¡ã‚¤ãƒ«ã‚’å‹•çš„ã«ä½œæˆ
    # - name: Create .env
    #   run: |
    #     echo "API_KEY=${{ secrets.API_KEY }}" >> .env
    #     echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
    #     echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
    #     echo "REDIRECT_URL=${{ secrets.REDIRECT_URL }}" >> .env

    - name: Generate code with build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Generate language_gen with build_runner
      run: |
        flutter pub get
        flutter gen-l10n
        flutter pub get

    - name: Run linter
      run: flutter analyze

    - name: Run tests with coverage
      run: flutter test --verbose --coverage --coverage-path=~/coverage/lcov.info

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file: ~/coverage/lcov.info

    # - name: Decode keystore
    #   run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > android/app/key.jks
    
    # - name: Create key.properties
    #   run: |
    #     echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
    #     echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
    #     echo "keyAlias=${{ secrets.ALIAS }}" >> android/key.properties
    #     echo "storeFile=key.jks" >> android/key.properties
    
    # - name: Build APK (Android)
    #   run: flutter build apk --release
    
    # - name: "Deploy apk ðŸš€"
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: release-apk
    #     path: build/app/outputs/flutter-apk/app-release.apk
    #     retention-days: 7
